/**
 * Verifies candidate exercise videos via YouTube oEmbed (confirms the video
 * exists, is embeddable, and records its real title + channel), then writes
 * the verified list to src/content/videos.ts.  Usage: npm run videos:verify
 * Review the output by eye — a clinician should confirm each video shows the
 * right variation before it goes to patients.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { VIDEO_CANDIDATES } from "../src/content/video-candidates";

type OEmbed = { title: string; author_name: string };

async function check(id: string): Promise<OEmbed | null> {
  const url = `https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}`;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    return (await res.json()) as OEmbed;
  } catch {
    return null;
  }
}

async function main() {
  const verified: { slug: string; youtubeId: string; title: string; source: string }[] = [];
  for (const c of VIDEO_CANDIDATES) {
    const info = await check(c.youtubeId);
    if (!info) {
      console.log(`✗ ${c.slug.padEnd(26)} ${c.youtubeId}  not found or not embeddable`);
      continue;
    }
    console.log(`✓ ${c.slug.padEnd(26)} ${c.youtubeId}  "${info.title}" — ${info.author_name}`);
    verified.push({ slug: c.slug, youtubeId: c.youtubeId, title: info.title, source: info.author_name });
  }
  const file = `/**
 * Curated video demonstrations for FORM's approved library.
 * Generated by scripts/verify-videos.ts — each entry passed YouTube oEmbed
 * verification. Clinics can override any of these with their own video.
 */
export type ExerciseVideoSeed = {
  slug: string;
  youtubeId: string;
  title: string;
  /** Channel or organization credited on the player. */
  source: string;
};

export const EXERCISE_VIDEOS: ExerciseVideoSeed[] = ${JSON.stringify(verified, null, 2)};
`;
  writeFileSync(path.join(process.cwd(), "src/content/videos.ts"), file);
  console.log(`\n${verified.length}/${VIDEO_CANDIDATES.length} verified → src/content/videos.ts`);
}

main();
